name: Simple CI

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "The version to build - defaults to SHA"
        default: ${{ github.sha }}

jobs:
  run-ci:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - run: npm install
    - run: npm pack
    - name: Rename tar
      run: mv lib-jitsi-meet*.tgz lib-jitsi-meet-${{ inputs.version }}.tgz
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ inputs.version }}
        body: "This is a release of lib-jitsi-meet version ${inputs.version}"
        files: lib-jitsi-meet-${{ inputs.version }}.tgz
